#.travis.yml

language: node_js
node_js:
- '8'

dist: trusty
sudo: true
cache:
  directories:
  - node_modules

addons:
  chrome: stable

install:
- npm install

script:
- ng build
- ng test --watch=false