#.travis.yml

language: node_js
node_js:
- '8'

dist: trusty
sudo: true
cache:
  directories:
  - node_modules

addons:
  chrome: stable

install:
- npm install

script:
- npm run build

notifications:
  slack:
    rooms:
      - courscollab2018:HRwgR54EPpeVvzRVDIwYc6BZ#team_supercopter_ci
